name: First Workflow

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Display a message
        run: echo "Hello, GitHub Actions!"

      - name: cat swapi.html
        run: cat swapi.html

      - name: echo secret
        run: echo ${{ secrets.DBPASSWORD }}

      - name: echo variable
        run: echo ${{ env.MYFATHER }}